# Generated by Django 2.2.6 on 2019-10-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Product_code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=255, max_digits=255)),
                ('quantity', models.IntegerField()),
                ('categories', models.ManyToManyField(to='Product.categories')),
            ],
        ),
    ]
